image: python:3.12.0

tests:
  stage: test      # For selecting small shared runners
  script:
    - pip install -r requirements.txt
    - echo "Executing unit tests..."
    - coverage run -m pytest -rsv --junit-xml=report.xml # Generate test report in junit format
    - coverage report # for displaying coverage in job logs
    - coverage xml    # for generating coverage.xml report
  coverage: '/^TOTAL.+?(\d+\%)$/'
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: report.xml
  interruptible: true
